bus/urls.py
"""Defines URL patterns for map app."""
from django.urls import path
from . import views

app_name = "bus"
urlpatterns = [
    # Bus driver
    path('busdriver/', views.busdriver_view, name='busdriver-page'),
    path('busposition-ajax/', views.bus_position_ajax, name='busposition-ajax'),
    path('bushasendedbroadcast-ajax/', views.deleteBusHasEndedBroadcastAJAX, name='bushasendedbroadcast-ajax'),

    # User-requested bus data
    path('busestarrival-ajax/', views.getEstimatedArrivalAJAX, name='busestarrival-ajax'),
    path('activebussesonroute-ajax/', views.getActiveBussesOnRouteAJAX, name='activebussesonroute-ajax'),
    path('busroutepolyline-ajax/', views.getBusRouteGmapsPolylineEncodingAJAX, name='busroutepolyline-ajax'),
    path('buslaststop-ajax/', views.updateLastBusStopManualAJAX, name='buslaststop-ajax'),

    # Transit log
    path('transitlogs/', views.transit_logs_view, name='transitlogs'),
    path('transitlogs/<int:log_id>', views.transit_log_entries_view, name='transitlogentries'),
    path('downloadtransitlogcsv-ajax', views.downloadTransitLogCSV_AJAX, name='downloadtransitlogcsv-ajax'),

    # Seats
    path('seatavailability-ajax/', views.updateBusSeatAvailabilityAJAX, name='seatavailability-ajax'),

    # Bus route
    path('admin-view/', views.admin_view, name='admin-view'),
    path('all-active-buses-ajax/', views.getAllActiveBussesAJAX, name='all-active-buses-ajax'),
]

communications/urls.py
"""Defines URL patterns for map app."""
from django.urls import path
from . import views

app_name = "communications"
urlpatterns = [
    # Announcements:
    path('announcements/', views.announcements_view, name='announcements'),

]

main/urls.py
"""Defines URL patterns for main."""
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    path('goals/', views.goals_objectives_view, name='goals-objectives'),
    path('mobile-architecture/', views.mobile_architecture_view, name='mobile-architecture'),
    path('security-privacy/', views.security_privacy_view, name='security-privacy'),
    path('arrival-time-accuracy-research/', views.arrival_time_accuracy_research_view, name='arrival-time-accuracy-research'),
    path('social-impact-research/', views.social_impact_research_view, name='social-impact-research'),
    path('management-dev-teams/', views.management_dev_teams_view, name='management-dev-teams'),
    path('fieldtest-gallary/', views.field_test_gallery_view, name='field-test-gallery'),

]

map/urls.py
"""Defines URL patterns for map app."""
from django.urls import path
from . import views

app_name = "map"
urlpatterns = [
    # Map:
    path('map/', views.map_hello_world, name='map'),
    path('routedetails-ajax/', views.getRouteDetailsAJAX, name='routedetails-ajax'),
    path('occupancy-status-ajax/', views.getBusColorDescriptionAJAX, name='occupancy-status-ajax'),

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    """Home page."""
    return render(request, 'main/index.html')


def goals_objectives_view(request):
    return render(request, "main/goalsobjectives.html")

def field_test_gallery_view(request):
    return render(request, "main/field_test_gallery.html")


def mobile_architecture_view(request):
    return render(request, "main/mobilearchitecture.html")


def security_privacy_view(request):
    return render(request, "main/security_privacy.html")


def arrival_time_accuracy_research_view(request):
    return render(request, "main/arrival_time_accuracy_research.html")


def social_impact_research_view(request):
    return render(request, "main/social_impact.html")


def management_dev_teams_view(request):
    return render(request, "main/management_dev_teams.html")

main/templates/main/arrival_time_accuracy_research.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}
    <style nonce="{{request.csp_nonce}}">
        #content-main {
            height: 100%;
            color: black;
            padding-top: 30px;
            padding-bottom: 30px;
            justify-content: center;
        }
    </style>
{% endblock %}


{% block content %}
    <div id="content-main" class="container-fluid">
        <div id="intro" class="bg-image shadow-2-strong">
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
                <div class="container-md p-3 mb-2 bg-white text-dark ">
                   <h3 style="text-align: center; ">Arrival Time Accuracy Research</h3>
                   <p> Providing accurate, real-time bus location information reduces riders’ wait times and thus the length of
                    their daily commutes, leaving more time for vocational, educational, and leisure activities. Our SmartSAT
                    mobile web app will track bus location using a combination of Google APIs, Google Live Transit Updates
                    service, and bus Global Positioning System (GPS) to improve the prediction accuracy of bus arrival time.
                  </p>

                    <div class="row">
                        <div class="col-md-12">
                            <h5>Proposed Work</h5>
                            <p>Existing approaches use GPS to collect real time location information of a vehicle to
                                predict public transport arrival times on bus stops. However, the evaluation of the proposed algorithm
                                shows errors in predicted times. In addition, issues related to GPS outages and location errors have not
                                been addressed. To address such issues, other approaches used the historical and real time location data to
                                determine the current location of a bus and to predict arrival time at a bus-stop. Results,
                                however, show mean error of 5 minutes in the arrival time prediction. To improve the arrival time
                                accuracy, we will use information provided by Direction API and Distance Matrix API of Google Maps,
                                Google's Live Transit Updates service, and Bus GPS to calculate bus travel times based on real-time
                                traffic data to obtain accurate real-time traffic data, compute travel times and predict the arrival time at a
                                bus-stop. Data analytics will then be used to assess the accuracy of the predicted arrival time by comparing
                                it with the actual bus arrival time. The study will also assess the accuracy of the current scheduled time by
                                comparing it with the actual bus arrival time. </p>
                        </div>
                    </div>
                    <h5>Methodology</h5>
                        <p> The primary outcome measure that will be used to evaluate our hypothesis is the arrival
                            time prediction error (i.e., the difference between the actual and predicted bus arrival times). The outcome
                            will be evaluated using multiple-trip data collected over the six VIA bus routes selected for this
                            project. We will measure the mean error (difference in time) between the actual arrival time and the
                            predicted one. Results will show the accuracy of predicted times, and whether this accuracy can be
                            improved. If the accuracy is improved, we will determine the accuracy of the scheduled times and if they
                            need to be changed.
                        </p>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

{% block footer %}
    {% include 'main/nsf_footer.html' %}
{% endblock footer %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- socket.io -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.5.1/socket.io.js" nonce="{{request.csp_nonce}}"
            integrity="sha512-9mpsATI0KClwt+xVZfbcf2lJ8IFBAwsubJ6mI3rtULwyM3fBmQFzj0It4tGqxLOGQwGfJdk/G+fANnxfq9/cew=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- jquery, ajax -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" nonce="{{request.csp_nonce}}"
            integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Bootstrap5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" nonce="{{request.csp_nonce}}"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!-- Icons (contact-us envelope, etc.) -->
    <link rel="stylesheet"  nonce="{{request.csp_nonce}}" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style nonce="{{request.csp_nonce}}">
        html, body {
            height: 100%;
            width: 100%;
            padding: 0;
            margin: 0;
        }

        body {
            display: flex;
            flex-direction: column;
        }

        header {
            position: sticky; /* using a fixed header is messy */
            position: -webkit-sticky;
            top: 0;
            z-index: 1000; /* force it to be the topmost element using a large number */
        }

        main {
            flex: auto;
        {#background-color: #ccc;#}
        }

        footer {
        }


    </style>

    {% block extend_head %}
    {% endblock %}
</head>

<body>

<header>
    {% include 'main/navbar.html' %}
</header>

<main role="main">
    {% block content %}
    {% endblock %}
</main>

{% block footer %}
{% endblock footer %}

<!-- Bootstrap5 JS (navbar collapse won't work without it; docs say to but before closing body tag) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" nonce="{{request.csp_nonce}}"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/field_test_gallery.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}
    <style nonce="{{ request.csp_nonce }}">

        .parent {
            margin-top: 5px;
            max-width: 85vw;
            max-height: 85vh;
            overflow: hidden;
        }

        .parent img {
            width: 100%;
            height: auto;
            display: block;
            object-fit: fill;
        }
        #carouselExampleCaptions span {
            background-color: #000000;
        }


    </style>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row align-self-center">

            <div id="carouselExampleCaptions" class="carousel slide">
                <div class="carousel-inner parent">
                    <div class="carousel-item active">
                        <img src="{% static 'main/img/Route51-Lee2.gif' %}" class="d-block w-100" alt="...">
                    </div>
                     <div class="carousel-item">
                        <img src="{% static 'main/img/Route51-Lee3.gif' %}" class="d-block w-100" alt="...">
                    </div>
                     <div class="carousel-item">
                        <img src="{% static 'main/img/Route51-Lee4.gif' %}" class="d-block w-100" alt="...">
                    </div>
                     <div class="carousel-item ">
                        <img src="{% static 'main/img/Route51-Lee5.gif' %}" class="d-block w-100" alt="...">
                    </div>
{#                     <div class="carousel-item ">#}
{#                        <img src="{% static 'main/img/Route64-51.gif' %}" class="d-block w-100" alt="...">#}
{#                    </div>#}
                     <div class="carousel-item">
                        <img src="{% static 'main/img/Route64-93.gif' %}" class="d-block w-100" alt="...">
                    </div>
{#                    <div class="carousel-item ">#}
{#                        <img src="{% static 'main/img/Route64-93-2.gif' %}" class="d-block w-100" alt="...">#}
{#                    </div>#}
{#                     <div class="carousel-item ">#}
{#                        <img src="{% static 'main/img/Route64-93-51-1.gif' %}" class="d-block w-100" alt="...">#}
{#                    </div>#}
{#                     <div class="carousel-item ">#}
{#                        <img src="{% static 'main/img/Route64-93-51-2.gif' %}" class="d-block w-100" alt="...">#}
{#                    </div>#}
{#                     <div class="carousel-item ">#}
{#                        <img src="{% static 'main/img/Route64-D-1.gif' %}" class="d-block w-100" alt="...">#}
{#                    </div>#}
{#                     <div class="carousel-item ">#}
{#                        <img src="{% static 'main/img/Route93-51-1.gif' %}" class="d-block w-100" alt="...">#}
{#                    </div>#}
{#                     <div class="carousel-item ">#}
{#                        <img src="{% static 'main/img/Route93-51-2.gif' %}" class="d-block w-100" alt="...">#}
{#                    </div>#}
                    <div class="carousel-item ">
                        <img src="{% static 'main/img/Route93-51-3.gif' %}" class="d-block w-100" alt="...">
                    </div>
{#                    <div class="carousel-item ">#}
{#                        <img src="{% static 'main/img/Route93-A1.gif' %}" class="d-block w-100" alt="...">#}
{#                    </div>#}
                    <div class="carousel-item ">
                        <img src="{% static 'main/img/Route93-A2.gif' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item ">
                        <img src="{% static 'main/img/Route93-A3.gif' %}" class="d-block w-100" alt="...">
                    </div>
{#                    <div class="carousel-item ">#}
{#                        <img src="{% static 'main/img/Route93-A4.gif' %}" class="d-block w-100" alt="...">#}
{#                    </div>#}
                    <div class="carousel-item ">
                        <img src="{% static 'main/img/Route93-A4-Attentionon Arrival times.gif' %}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </div>

{% endblock %}


{% block footer %}
    {% include 'main/nsf_footer.html' %}
{% endblock footer %}

main/templates/main/goalsobjectives.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}
    <style nonce="{{request.csp_nonce}}">
        #content-main {
            height: 100%;
            color: black;
            justify-content: center;
        }
    </style>
{% endblock %}


{% block content %}
    <div id="content-main" class="container">
        <div class="row">
            <div class="col-md-5 align-self-center">
                <style nonce="{{request.csp_nonce}}"> #shutterstockIMG{max-width: 100%;}</style>
                <img src="{% static 'main/img/shutterstock_627370652.jpg' %}" alt="shutterstock_627370652.jpg" id="shutterstockIMG">
            </div>
            <div class="col-md-7 align-self-center">
                <style nonce="{{request.csp_nonce}}"> #article{ margin-bottom: 5%;margin-top: 5%;}</style>
                <article class="container d-flex flex-column align-items-start justify-content-md-start" id="article">
                    <style nonce="{{request.csp_nonce}}"> #goalsObj{ text-align: center;}</style>
                    <h3 id="goalsObj">Goals and Objectives</h3>
                    <!-- <article class="text-white mb-0"> -->
                    <!-- <article class="text-white mb-0" style="background-color: rgba(51, 46, 112, 0.02);"> -->

                    <p> MySmartSA utilizes a multipronged approach to conduct quantitative and qualitative research
                        using secure intelligent technology, build intra- and inter-disciplinary research capacity
                        at A&M-SA, build research partnerships between A&M-SA and SA VIA Metropolitan Transit (VIA
                        Transit) to facilitate data driven transit planning decisions, and increase the competitiveness
                        of
                        A&M-SA faculty-student research for future CISE grants. The MySmartSA app will be customizable
                        and
                        will include real-time bus arrival information, notices when seating is limited, instant alert
                        messages for schedule changes and other important information, and interactive features to
                        directly collect data from riders about their commute experience. All services will be available
                        in both English and Spanish. Researchers and students from
                        diverse disciplines (sociology, computer science, cyber security, & information science)
                        will work collaboratively to achieve project success. </p>

                    <p>The objectives of the MySmartSA are to:</p>
                    <p>(1) improve the accuracy of bus arrival time reporting </p>
                    <p>(2) provide up-to-date information about seating availability and important transit alerts</p>
                    <p> (3) collect data that will be used to improve rider satisfaction and inclusivity of VIA
                        transit </p>

                </article>
            </div>

        </div>
    </div>

{% endblock %}


{% block footer %}
    {% include 'main/nsf_footer.html' %}
{% endblock footer %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}

    <style nonce="{{request.csp_nonce}}">
        #intro {
            height: 100%; /* div height */

            background-image: url("{% static 'main/img/background_image.jpeg' %}");
            background-size: cover; /* background image size, 'cover' forces image to cover entire container */
            background-position: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }

    </style>

{% endblock %}


{% block content %}

    <div id="intro" class="container-fluid">
        <div class="container">
            <div class="row">
                <style nonce="{{request.csp_nonce}}"> #socialImpact{text-align: center;}</style>
                <h3 class="text-white mb-0" id="socialImpact">
                    Building a Smart Mobility Network for the San Antonio Transit to Improve Transit Service and
                    Social Impact (SmartSA)
                </h3>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <a href="{% url 'map:map' %}" title="Go to Map">
                        <style nonce="{{request.csp_nonce}}"> #mapButton{margin-left: 12.5%; margin-top: 5%; min-width: 75%; margin-bottom: 5%;
                            object-fit: scale-down}</style>
                        <img src="{% static 'main/img/MapButton.png' %}" alt="MAP" id="mapButton">
                    </a>
                    <a href="https://tamusa.co1.qualtrics.com/jfe/form/SV_0NT7LynF4lUNuNo"
                       title="Take the Survey" nonce="{{request.csp_nonce}}">
                        <style nonce="{{request.csp_nonce}}"> #surveyButton{margin-left: 12.5%; margin-top: 5%; min-width: 75%; margin-bottom: 5%;
                        object-fit: scale-down;}</style>
                        <img src="{% static 'main/img/SurveyButton.png' %}" alt="Survey" id="surveyButton">
                    </a>
                </div>
                <div class="col-md-9">
                    <a href="https://tamusa.co1.qualtrics.com/jfe/form/SV_0NT7LynF4lUNuNo"
                       title="Take the Survey">
                        <style nonce="{{request.csp_nonce}}"> #flyer{margin-top: 1.5%; object-fit: cover;}</style>
                        <img src="{% static 'main/img/flyer.png' %}" class="img-fluid" alt="Survey" id="flyer">
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}
    {% include 'main/nsf_footer.html' %}
{% endblock footer %}

main/templates/main/mobilearchitecture.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}
    <style nonce="{{request.csp_nonce}}">
        #content-main {
            height: 100%;
            color: black;
            padding-top: 30px;
            padding-bottom: 30px;
            justify-content: center;
        }
    </style>
{% endblock %}


{% block content %}
    <div id="content-main" class="container">
        <div class="row">
            <style nonce="{{request.csp_nonce}}"> #mobAppArch{text-align: center; }</style>
            <h3 id="mobAppArch">Mobile App Architecture</h3>
            <p> The backbone of the MySmartSA application is Web Architecture. All designed interfaces
                will respond to different screen sizes of devices and different browsers and will run well on any mobile
                phone, tablet, laptop, and desktop. This project integrates security into agile software
                development. Some practical solutions are suggested, like integrating a static analysis tool into an
                IDE, performing dependency/open-source security checks whenever possible, and configuring
                dynamic test tools into CI/CD pipelines during development and testing. While the automation of security
                checks at each stage of the agile process is
                desired, rolling out security practices at some levels is also recommended. To dynamically respond to
                changing demands and to ensure the protection of rider’s personal data and privacy, web app development
                for this project
                practices agile development with the integration of security. The security testing
                adapts the recommended security roadmap without a SAST vendor for CD/CI.
            </p>
        </div>


        <div class="row">
            <div class="col-md-6">
                <h5>Development Methodology</h5>
                <p>'Providing Real-Time Bus Arrivals' be implemented with Google Maps Platform web
                    services. Google Maps' JavaScript API are the main APIs to retrieve the latest Maps and Routes in
                    the
                    development, where real-time traffic conditions are constantly updated with routes. Directions for
                    transit are obtained by Direction API, and Distance Matrix API is used to calculate travel times
                    based on
                    real-time traffic and distance for multiple stops on a route. Utilizing these APIs, we can
                    conveniently build
                    customized transit maps to fit our project needs. With some exceptions, the mobile web app routes
                    are
                    considered faster and cheaper than the native iOS or Android mobile app routes that use iOS or
                    Android
                    SDK. The Javascript API is chosen for this project because of its capability to enable map controls
                    and gestures for any mobile devices running on web browsers, to provide directions services with
                    realtime
                    traffic information using a form of public transit, and their exclusive support of transit layer
                    with
                    public transport routes, and easy integration with other transit web sites.
                </p>
            </div>
            <div class="col-md-6 align-self-center">
                <a href="{% static 'main/img/mobile_architecture_image.png' %}">
                    <style nonce="{{request.csp_nonce}}"> #mobile_architecture_image{max-width: 100%;}</style>
                    <img src="{% static 'main/img/mobile_architecture_image.png' %}" alt="Mobile Architecture" id="mobile_architecture_image">
                </a>
            </div>
        </div>

    </div>

{% endblock %}


{% block footer %}
    {% include 'main/nsf_footer.html' %}
{% endblock footer %}

main/templates/main/navbar.html
<nav id="navbar" class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'map:map' %}">Map</a>
                <a class="nav-link" href="{% url 'communications:announcements' %}">Announcements</a>

                {% if perms.bus.access_busdriver_pages %}
                    <a class="nav-link" href="{% url 'bus:busdriver-page' %}">Bus</a>
                {% endif %}
                {% if user.is_superuser %}
                    <a class="nav-link" href="{% url 'bus:admin-view' %}">All Routes View</a>
                    <a class="nav-link" href="{% url 'bus:transitlogs' %}">Transit-Logs</a>
                {% endif %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Project
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'main:goals-objectives' %}">Goals & Objectives</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'main:mobile-architecture' %}">Mobile Web App
                            Architecture</a></li>

                        <li><a class="dropdown-item" href="{% url 'main:security-privacy' %}">Security & Rider Privacy</a>
                        </li>

                        <li><a class="dropdown-item" href="{% url 'main:arrival-time-accuracy-research' %}">Arrival Time Accuracy Research</a>
                        </li>

                        <li><a class="dropdown-item" href="{% url 'main:social-impact-research' %}">Social Impact Research</a>
                        </li>

                        <li><a class="dropdown-item" href="{% url 'main:management-dev-teams' %}">Management & Development Teams</a>
                        </li>

                        <li><a class="dropdown-item" href="{% url 'main:field-test-gallery' %}">Field Test Gallery</a></li>

                    </ul>
                </li>

                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <style nonce="{{request.csp_nonce}}"> #nav-link{ color: whitesmoke}</style>
                        <a class="nav-link" id="nav-link" href="/admin">Hello {{ user.username }}</a>
                    {% else %}
                        <style nonce="{{request.csp_nonce}}"> #nav-link-disabled{ color: whitesmoke}</style>
                        <a class="nav-link disabled" id="nav-link-disabled">Hello {{ user.username }}</a>
                    {% endif %}
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                {% else %}
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>

            <div class="navbar-nav ms-auto">
                {# TODO create page for feedback submission #}
                <a class="nav-link" href="/" title="Send us your Feedback">
                    <style nonce="{{request.csp_nonce}}"> #envelope {color: white}</style>
                    <i class="fa fa-envelope" id="envelope" ></i>
                </a>
                <a class="nav-link" href="https://www.linkedin.com">
                    <style nonce="{{request.csp_nonce}}"> #linkedin{color: white} </style>
                    <i class="fa fa-linkedin" id="linkedin" ></i>

                </a>
                <a class="nav-link" href="https://github.com/" rel="nofollow" target="_blank">
                    <style nonce="{{request.csp_nonce}}"> #github{color: white}</style>
                    <i class="fa fa-github" id="github"></i>
                </a>
            </div>

        </div>
    </div>
</nav>

main/templates/main/nsf_footer.html
{% load static %}
{% block extend_head %}
<style nonce="{{request.csp_nonce}}">
@media screen and (max-width: 600px) {
        #nsf-log {
                display: none;
        }
}
    </style>
{% endblock %}
<footer class="bg-dark">
    <!-- Grid container -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-auto" id="nsf-log">
                <img class="img-fluid" src="{% static 'main/img/NSF100.png' %}" alt="NSF logo" style="width: 60px">
            </div>
            <div class="col">
                <p class="text-white mb-0">
                    This material is based upon work supported by the National Science Foundation under Grant No. <a
                        href="https://www.nsf.gov/awardsearch/showAward?AWD_ID=2131193">
                    <strong>2131193</strong></a>. Any opinions, findings, and conclusions, or recommendations expressed in
                    this material are those of the author(s) and do not necessarily reflect the views of the National
                    Science Foundation.
                </p>
            </div>
        </div>
    </div>

    <!-- Copyright -->
    <!-- <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div> -->
    <!-- Copyright -->
</footer>