bus/urls.py
"""Defines URL patterns for map app."""
from django.urls import path
from . import views

app_name = "bus"
urlpatterns = [
    # Bus driver
    path('busdriver/', views.busdriver_view, name='busdriver-page'),
    path('busposition-ajax/', views.bus_position_ajax, name='busposition-ajax'),
    path('bushasendedbroadcast-ajax/', views.deleteBusHasEndedBroadcastAJAX, name='bushasendedbroadcast-ajax'),

    # User-requested bus data
    path('busestarrival-ajax/', views.getEstimatedArrivalAJAX, name='busestarrival-ajax'),
    path('activebussesonroute-ajax/', views.getActiveBussesOnRouteAJAX, name='activebussesonroute-ajax'),
    path('busroutepolyline-ajax/', views.getBusRouteGmapsPolylineEncodingAJAX, name='busroutepolyline-ajax'),
    path('buslaststop-ajax/', views.updateLastBusStopManualAJAX, name='buslaststop-ajax'),

    # Transit log
    path('transitlogs/', views.transit_logs_view, name='transitlogs'),
    path('transitlogs/<int:log_id>', views.transit_log_entries_view, name='transitlogentries'),
    path('downloadtransitlogcsv-ajax', views.downloadTransitLogCSV_AJAX, name='downloadtransitlogcsv-ajax'),

    # Seats
    path('seatavailability-ajax/', views.updateBusSeatAvailabilityAJAX, name='seatavailability-ajax'),

    # Bus route
    path('admin-view/', views.admin_view, name='admin-view'),
    path('all-active-buses-ajax/', views.getAllActiveBussesAJAX, name='all-active-buses-ajax'),
]

bus/views.py
import ast
import datetime
import json
from datetime import datetime
from datetime import timedelta

import googlemaps
import polyline
from django.conf import settings
from django.utils import timezone

import pytz
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, HttpResponse
from googlemaps.directions import directions

import commons.helper
from .distancematrixcalcs import calc_duration, calc_est_arrival_times, calc_est_arrival_times_opt
from .models import Bus, BusRoute, BusRouteDetails, BusSchedule, BusStop
from .models import TransitLog, BusArrivalLog, BusArrivalLogEntry

BUS_SCHEDULE_INTERVAL_MINUTES = 40

BUS_STOP_ARRIVAL_PROXIMITY = 10  # meters
ARRIVAL_LOG_FREQUENCY = 60  # seconds
gmaps = googlemaps.Client(key=settings.GOOGLE_PYTHON_API_KEY)


"""
Bus Driver page
"""


@login_required
@permission_required('bus.access_busdriver_pages', raise_exception=True)
def busdriver_view(request):
    context = {'allRoutes': commons.helper.getAllActiveRoutesDropDown(),
               'google_api_key': settings.GOOGLE_MAP_API_KEY}
    return render(request, "bus/busdriver_2.html", context)


def getScheduleDayOfWeekLetter(date):
    today = date.weekday()

    if today == 6:  # Sunday
        return "F"
    elif today == 5:  # Saturday
        return "S"
    else:  # Weekday
        return "W"


def getEstimatedArrivalAJAX(request):
    """
    Called by BusStop js class method. User is requesting position of bus(es) for a route.
    :param request:
    :return:
    """
    # extract data from request,  route and bus_stop ID
    user_data = ast.literal_eval(request.GET.get('data'))
    user_selected_route = user_data.get('route')
    user_selected_bus_stop = user_data.get('bus_stop_id')
    calc_schedule = user_data.get('calc_schedule')
    selected_bus_stop_id = int(user_selected_bus_stop)
    result = {
        'est_arrival': "",
        'scheduled_arrival': ""
    }

    # TODO filter BusRoute models

    # get BusStop instance
    busStop = BusRouteDetails.objects.get(parent_route=user_selected_route,
                                          bus_stop__stop_id=int(user_selected_bus_stop)).bus_stop
    busStopCoord = busStop.getCoordinates()

    # filter Bus models by route (for now)
    # assumptions:  only one bus at anytime per route
    bus = Bus.objects.filter(route=user_selected_route).first()  # TODO filter for multiple busses
    bus.route = BusRoute.objects.filter(pk=user_selected_route).first()

    dateTimeNow = datetime.now()
    day_of_week = getScheduleDayOfWeekLetter(dateTimeNow)
    next_arrival = BusSchedule.objects.filter(bus_route_id=user_selected_route, day_of_week=day_of_week,
                                              bus_stop=busStop,
                                              scheduled_time__gte=dateTimeNow.time().strftime('%H:%M:%S')).first()
    if next_arrival is not None:
        result[
            'scheduled_arrival'] = f'{next_arrival.scheduled_time.strftime("%I:%M %p")} on {dateTimeNow.date().strftime("%B %d, %Y")}'
    if bus is None:
        return HttpResponse(json.dumps(result))

    busCoord = bus.getCoordinates()
    # send Bus obj coords and BusStop obj coords to dist matrix calc
    # travelDuration = calc_duration(busCoord, busStopCoord)
    # Todo
    """
    If the latest bus stop index can't get from the bus driver side, it needs to calculate which two bus stops are the bus between
    So far, couldn't find a accurate algorithm to do this. Tried polyline and haversine, not that accuracy on some special condition.
    """
    bus_stop_id = BusStop.objects.get(stop_id=selected_bus_stop_id).id
    route_index_id = BusRouteDetails.objects.get(bus_stop_id=bus_stop_id, parent_route_id=user_selected_route).route_index
    travelDuration = calc_est_arrival_times_opt(bus.route, bus.latitude, bus.longitude, bus.latest_route_stop_index, route_index_id)
    # if 'duration' in travelDuration['rows'][0]['elements'][0].keys():
    #     result['est_arrival'] = travelDuration['rows'][0]['elements'][0]['duration']['text']
    next_arrival_est_time = dateTimeNow + timedelta(
        seconds=travelDuration[route_index_id]['rows'][0]['elements'][0]['duration']['value'])
    result['scheduled_arrival'] = \
        f'{next_arrival_est_time.strftime("%I:%M %p")} on {dateTimeNow.date().strftime("%B %d, %Y")}'
    result['est_arrival'] = travelDuration[route_index_id]['rows'][0]['elements'][0]['duration']['text']
    # return estimated arrival time result to user
    return HttpResponse(json.dumps(result))


def getActiveBussesOnRouteAJAX(request):
    # extract the data from the request
    user_data = ast.literal_eval(request.GET.get('data'))
    user_selected_route = user_data.get('route')

    # filter for all busses active on user-selected route
    busObjs = Bus.objects.filter(route=user_selected_route)

    # bus data to send back to client
    bus_data = {bus.id: {'selected_route': bus.route.pk, 'bus_lat': bus.latitude, 'bus_lng': bus.longitude,
                         'bus_color': bus.getBusColorStaticUrl()} for bus in busObjs}

    return HttpResponse(json.dumps(bus_data))

def getAllActiveBussesAJAX(request):
    # filter for all busses active on user-selected route
    busObjs = Bus.objects.all()

    # bus data to send back to client
    bus_data ={}
    for bus in busObjs:
        if bus.route.pk in bus_data:
            bus_data[bus.route.pk].append({'bus_id': bus.id, 'bus_lat': bus.latitude, 'bus_lng': bus.longitude,
                         'bus_color': bus.getBusColorStaticUrl(), 'title': f'{bus.driver} - {bus.route.name}'})
        else:
            bus_data[bus.route.pk] = [{'bus_id': bus.id, 'bus_lat': bus.latitude, 'bus_lng': bus.longitude,
                         'bus_color': bus.getBusColorStaticUrl(), 'title': f'{bus.driver} - {bus.route.name}'}]

    return HttpResponse(json.dumps(bus_data))


def getBusRouteGmapsPolylineEncodingAJAX(request):
    """
    Returns polyline encoding (str) from Google Maps DirectionsService API
    for user-selected route.
    """
    # extract the data from the request
    user_data = ast.literal_eval(request.GET.get('data'))
    user_selected_route = user_data.get('route')
    # get the BusRoute instance and return the polyline encoding
    busRoute = BusRoute.objects.filter(id=user_selected_route).first()

    bus = Bus.objects.filter(route=user_selected_route).first()


    if bus is None:
        to_send = {'polyline_encoding': busRoute.gmaps_polyline_encoding,
                   'polyline_bounds': ast.literal_eval(busRoute.gmaps_polyline_bounds)}
    else:
        latest_route_stop_index = bus.latest_route_stop_index

        busStop = BusRouteDetails.objects.get(parent_route=user_selected_route,
                                              route_index=latest_route_stop_index).bus_stop
        busStopCoord = busStop.getCoordinates()
        first_stop_coord = busRoute.first_stop.getCoordinates()
        bus_coord = bus.getCoordinates()

        directions_results = []
        decoded_coordinates = []
        # Get the directions
        directions_results.append(directions(gmaps, origin=first_stop_coord, destination=busStopCoord, mode="transit",
                                       transit_mode="bus"))
        directions_results.append(directions(gmaps, origin=busStopCoord, destination=bus_coord, mode="driving"))

        # Check if the directions_result is not empty
        for directions_result in directions_results:
            if directions_result:
                # Get the first route from the directions result
                route = directions_result[0]
                polyline_str = route['overview_polyline']['points']
                coordinates = polyline.decode(polyline_str)
                decoded_coordinates.extend(coordinates)
                # Get the polyline from the route

        combined_polyline = polyline.encode(decoded_coordinates)
        to_send = {'polyline_encoding': combined_polyline,
                   'polyline_bounds': ast.literal_eval(busRoute.gmaps_polyline_bounds)}

    return HttpResponse(json.dumps(to_send))


@login_required
@permission_required('bus.access_busdriver_pages', raise_exception=True)
def bus_position_ajax(request):
    """
    data format:
    {
         'selected_route': routeSelect.value,
         'latitude': geolocationCoordinates.latitude,
         'longitude': geolocationCoordinates.longitude,
         'accuracy': geolocationCoordinates.accuracy,
         'speed': geolocationCoordinates.speed,
         'heading': geolocationCoordinates.heading
     }
    """
    if request.method == 'GET':
        # extract bus position out of request
        ajax_data = ast.literal_eval(request.GET.get('posData'))
        selected_route = ajax_data['selected_route']
        bus_lat = ajax_data['latitude']
        bus_lng = ajax_data['longitude']
        active_bus_id = ajax_data['active_bus_id']

        # Get current time
        # datetime_now = datetime.utcnow()  # original code
        # time_zone = pytz.timezone('US/Central')
        datetime_now = datetime.now()
        # datetime_now = timezone.now()

        # Get BusRoute instance from db
        busRoute = BusRoute.objects.filter(pk=selected_route).first()

        # Check if the Bus instance exists already
        if active_bus_id != -1:
            bus = Bus.objects.filter(pk=active_bus_id).first()
        else:
            bus = Bus.objects.filter(driver=request.user.username,route_id=selected_route).first()

        if bus is None:
            # Create BusArrivalLog
            arrivalLog = BusArrivalLog(route_id=busRoute.id)
            arrivalLog.driver = request.user.username
            arrivalLog.save()

            # Create a Bus instance
            bus = Bus(driver=request.user.username)
            bus.route = busRoute
            bus.arrival_log_id = arrivalLog.id
            bus.start_time = datetime_now

bus/templates/bus/transit_log_entries.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}

 <script type="text/javascript">

        function DownloadFile(log_id) {
            //Set the File URL.
            jQuery.ajax({
                url: "{% url 'bus:downloadtransitlogcsv-ajax' %}",
                data: {'data': JSON.stringify(log_id)},
                // ^the leftmost "data" is a keyword used by ajax and is not a key that is accessible
                // server-side, hence the object defined here
                type: "GET",
                dataType: 'json',  // in this example HTML data is sent back via HttpResponse in views.py,
                success: function (data) {
                    let fileName = `${data.filename}.csv`
                    let json_data = data.json_data

                    if (json_data.length < 1)
                        return;

                    const newline = "\r\n";
                    const delim = ",";
                    let csvContent = "data:text/csv;charset=utf-8," + Object.keys(json_data[0]).join(delim) + newline;

                    json_data.forEach(function (rowObj) {
                        csvContent += Object.values(rowObj).join(delim) + newline;
                    })

                    // To download file with a custom name, must create a hidden <a> DOM node and set its download attribute
                    var encodedUri = encodeURI(csvContent);
                    var link = document.createElement("a");
                    link.setAttribute("href", encodedUri);
                    link.setAttribute("download", fileName);  // Name of downloaded file is set here
                    document.body.appendChild(link); // Required for FF
                    link.click(); // This will download the data file
                }
            });
        }
    </script>

{% endblock %}


{% block content %}
    <div class="container">
        <h4>Transit Log: {{ transit_log }}</h4>
        <input type="button" value="Download CSV File" onclick="DownloadFile({{ transit_log.id }})"/>
        <br><br>
        <h5>Entries:</h5>
        <ul>
            {% for entry in entries %}
                <li>
                    <p>{{ entry.time_stamp|date:'Y-m-d H:i:s' }}, Lat: {{ entry.latitude }}, Lng: {{ entry.longitude }}</p>
                </li>
            {% empty %}
                <li>There are no entries yet.</li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}

bus/templates/bus/transit_logs.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}



{% endblock %}


{% block content %}
    <div class="container">
        <h4>Transit Logs:</h4>

        <ul>
            {% for log in transit_logs %}
                <li>
                    <a href="{% url 'bus:transitlogentries' log.id %}">{{ log.date_added|date:'M d, Y H:i:s' }}, {{ log.bus_route.name }}, {{ log.driver }}</a>
                </li>
            {% empty %}
                <li>There are no transit logs yet.</li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}